### ISSUE TITLE
Ignore difference in a certain area of a web page

### ISSUE THREAD

**Issue by donwelsh** [kazurayam/VisualTestingByImagemagickInKatalonStudio#2]
Hello,

Is it possible to ignore any differences in a certain area of a web page? For example on the web pages being compared lets say at the bottom of the page there is a date and time shown and I do not want the time to be counted as a difference as it will always be different and that is ok. So I do not want it to be flagged red as a difference.

Thanks

**Comment by kazurayam** [comment]
I can propose to you an immediate workaround and an idea to be considered in future.

(1) what's possible now

See https://github.com/kazurayam/VisualTestingInKatalonStudio/blob/master/Scripts/Main/ImageDiff/Script1535336589503.groovy 
```
// make ImageDiff files in the ./Materials/ImageDiff directory
new ImageCollectionDiffer(mr).makeImageCollectionDifferences(
		materialPairs,
		new TCaseName(GlobalVariable.CURRENT_TESTCASE_ID),  // 'Test Cases/Main/ImageDiff'
		3.68)   // criteriaPercentage: if the difference is bigger than 3.36% then the test case is falgged red as FAILURE
```
You can change this as
```
// make ImageDiff files in the ./Materials/ImageDiff directory
new ImageCollectionDiffer(mr).makeImageCollectionDifferences(
		materialPairs,
		new TCaseName(GlobalVariable.CURRENT_TESTCASE_ID),  // 'Test Cases/Main/ImageDiff'
		50.0)     // criteriaPercentage: if the difference is bigger than 50.0% then the test case is falgged red as FAILURE
```
If the actual difference detected is 20.0%, which is smaller the given criteria, then your test case will pass, not fail.

You can set any number (0<=N<=100) for the criteriaPercentage. If you give larger number, then your test will get more tolerant to insignificant differences, in other words less sensitive to possible significant ones.


(2) what's desired for future

>Is it possible to ignore any differences in a certain area of a web page?

Not implemented yet. But I know how to implement it in future. The aAhot supports Screenshot comparison with ignoring certain element in the target page:
- https://github.com/pazone/ashot#screenshot-comparison

All I need to do is to change my codes to utilize the `.addIgnoredElement(By by)` feature when test case code takes screenshots.

**Comment by donwelsh** [comment]
Hi Kaz,

Thanks for the response and all your nice work you do for the Katalon community. That would be awesome if you could change your code to optionally utilize the .addIgnoredElement(By by) feature when test case code takes screenshots.

Thanks!

**Comment by donwelsh** [comment]
What do you think about turning this into a plugin? Have you looked at the plugin beta yet?

Thanks

**Comment by kazurayam** [comment]
I am working on a enhancement of Visual Testing in Katalon Studio.  It will support 2 types of testing approach.
- **Twins** : compare 2 should-be-identical URLs at a time. This is the existing feature.
- **Chronos** : compare latest and previous screenshots of a URL. This is being developed.

Twins enables me to compare the development environment against the development environment at a time. Twins helps me to make sure I have no silly mistakes in the development environment.

Chronos will have different value. Chronos will enable me to compare my system **before/after the upgrades in the production services**. Chronological verification. This will make me 100% sure I have no silly mistakes injected due to changes made for app/db/os/network in the production environment.

Once I have done Chronos, I will consider making my tool set a plugin.

I have not looked at plugin beta yet. One reasone is that current plugin build process uses Maven. I prefer Gradle to maven. I am waiting for Katalon team to create Gradle-powered version.

**Comment by kazurayam** [comment]
donwelsh,

By the way, are you Katalon Team member? or a user?

**Comment by donwelsh** [comment]
Will your enhancement you are working on include the utilize the `.addIgnoredElement(By by)` feature you mentioned?

I am just a user. I appreciate all you contribute to the Katalon community!

Thanks

**Comment by kazurayam** [comment]
>Will your enhancement you are working on include the utilize the `.addIgnoredElement(By by)` feature you mentioned?

YES. I have done 90% of the work required. 

I have changed a few custom keywords involved in taking screenshots with taking `.addIgnoredElement(By by)` into account.

The rest I need to do is to update the "Visual Testing in Katalon Studio" sample codes and documentation to cover the "igore specific web elements" feature. I will finish it this weekend.

**Comment by kazurayam** [comment]
I have updated [VisualTestingInKatlaonStudio](https://github.com/kazurayam/VisualTestingInKatalonStudio) to version 1.8.0.

This version supported a new feature "ignoring web elements". See [Step by step instruction, section #10](https://github.com/kazurayam/VisualTestingInKatalonStudio/blob/master/docs/Step_by_step_instruction.md) for detail.

**Comment by donwelsh** [comment]
Thanks! I'm looking forward to trying it out.
